/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/avatar.glb 
*/
import React, { useEffect, useRef } from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useControls } from 'leva'
import * as THREE from "three"

export const Avatar = (props:any) => {
  const { animation, wireframe } = props
  const { headFollow, cursorFollow } = useControls({
    headFollow: false,
    cursorFollow: false,
  })
  const { scene } = useGLTF('/assets/models/avatar.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const group = useRef<THREE.Group | null>(null!)
  const { nodes, materials } = useGraph(clone)
  
  // Cast nodes to SkinnedMesh type for geometry and skeleton access
  const meshNodes = nodes as Record<string, THREE.SkinnedMesh>

  const { animations: typingAnimation } = useFBX("/animations/typing.fbx") 
  const { animations: standingAnimation } = useFBX("/animations/standing.fbx") 
  const { animations: fallingAnimation } = useFBX("/animations/falling.fbx") 


  typingAnimation[0].name = "Typing"
  standingAnimation[0].name = "Standing"
  fallingAnimation[0].name = "Falling"

  const { actions } = useAnimations([typingAnimation[0], standingAnimation[0], fallingAnimation[0]] , group)

  useFrame((state) => {
    if(headFollow) {
        group.current?.getObjectByName("Head")?.lookAt(state.camera.position)
    }

    if(cursorFollow) {
        const target = new THREE.Vector3(state.mouse.x, state.mouse.y, 1)
        group.current?.getObjectByName("Spine2")?.lookAt(target)
    }
  })


  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.5).play()
    return () => {
        actions[animation]?.reset().fadeOut(0.5)
    }
  }, [actions, animation])

  useEffect(() => {
    Object.values(materials).forEach((material: any) => {
        material.wireframe = wireframe
    })
  }, [wireframe, materials])

  return (
    <group {...props} ref={group} dispose={null}>
        <group rotation-x={-Math.PI / 2}>
        <primitive object={nodes.Hips} />
        <skinnedMesh frustumCulled={false} geometry={meshNodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={meshNodes.Wolf3D_Hair.skeleton} />
        <skinnedMesh frustumCulled={false} geometry={meshNodes.Wolf3D_Glasses.geometry} material={materials.Wolf3D_Glasses} skeleton={meshNodes.Wolf3D_Glasses.skeleton} />
        <skinnedMesh frustumCulled={false} geometry={meshNodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={meshNodes.Wolf3D_Body.skeleton} />
        <skinnedMesh frustumCulled={false} geometry={meshNodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={meshNodes.Wolf3D_Outfit_Bottom.skeleton} />
        <skinnedMesh frustumCulled={false} geometry={meshNodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={meshNodes.Wolf3D_Outfit_Footwear.skeleton} />
        <skinnedMesh frustumCulled={false} geometry={meshNodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={meshNodes.Wolf3D_Outfit_Top.skeleton} />
        <skinnedMesh frustumCulled={false} name="EyeLeft" geometry={meshNodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={meshNodes.EyeLeft.skeleton} morphTargetDictionary={meshNodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={meshNodes.EyeLeft.morphTargetInfluences} />
        <skinnedMesh frustumCulled={false} name="EyeRight" geometry={meshNodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={meshNodes.EyeRight.skeleton} morphTargetDictionary={meshNodes.EyeRight.morphTargetDictionary} morphTargetInfluences={meshNodes.EyeRight.morphTargetInfluences} />
        <skinnedMesh frustumCulled={false} name="Wolf3D_Head" geometry={meshNodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={meshNodes.Wolf3D_Head.skeleton} morphTargetDictionary={meshNodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={meshNodes.Wolf3D_Head.morphTargetInfluences} />
        <skinnedMesh frustumCulled={false} name="Wolf3D_Teeth" geometry={meshNodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={meshNodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={meshNodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={meshNodes.Wolf3D_Teeth.morphTargetInfluences} />
        </group>
    </group>

  )
}

useGLTF.preload('/assets/models/avatar.glb')
useFBX.preload('/animations/falling.fbx')
useFBX.preload('/animations/standing.fbx')
useFBX.preload('/animations/typing.fbx')
